meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: rsyslog-kafka
    templates:
    - name: rsyslog-kafka
      release: rsyslog-kafka
    - name: gomkafka
      release: rsyslog-kafka
    - name: sauron
      release: rsyslog-kafka
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( merge ))

networks: (( merge ))

properties:
  rsyslog_kafka:
    brokers:
      - localhost:9092
    topic: boshrelease_rsyslog_kafka
    org: myorg
    space: myspace
    service: myservice
    index: 4012
